"""Command IO smoke tests (Tier 1): TNEP "observer" models (dump_dipole, dump_polarizability).

GPUMD's own output is the ground truth here, per project principle: calorine's separately
maintained CPU reference implementation (CPUNEP, calorine.nep.get_polarizability) is not
guaranteed to support the same features and is not used to validate numeric correctness, in this
file or elsewhere in this suite going forward. Correctness is instead judged the same way
test_regression.py judges bulk_bazro3 -- against a golden reference generated by this repo's own
gpumd binary (conftest.py's compare_or_update_golden), regenerated only via --update-golden.

TNEP models are "observer" models: they run *alongside* a separate PES model rather than
replacing it. The PES model is supplied with `potential`, while the TNEP response model is
passed directly to `dump_dipole` or `dump_polarizability` -- see gpumd_pytest_suite_spec.md's
"TNEP fixtures" section. This doesn't fit the calculator/model_type
fixture pattern used elsewhere in this suite (no single model file, no CPUNEP/GPUNEP A/B
comparison to make), so each case wires up its own fixed (structure, PES model, TNEP model)
triple directly rather than sweeping the structure x model_type matrix -- the same reasoning
test_regression.py already applies to bulk_bazro3. The run.in construction pattern (one explicit
PES `potential` line plus the response model on the dump command) mirrors the existing manual
tests at tests/gpumd/dump_dipole/test_dump_dipole.py and
tests/gpumd/dump_polarizability/test_dump_polarizability.py, which remain the reference for
run.in syntax, not for numeric values.
"""
import numpy as np
import pytest

from conftest import MODELS_DIR, compare_or_update_golden, make_bulk_bazro3, make_bulk_water
from io_helpers import CommandIOCase, run_and_check

pytestmark = pytest.mark.fast

TNEP_CASES = {
    'dipole_water': dict(
        structure_builder=make_bulk_water, pes_model='nep_water.txt',
        tnep_model='tnep-water-polarization.txt', dump_command='dump_dipole',
        expected_output_file='dipole.out'),
    'polarizability_bazro3': dict(
        structure_builder=make_bulk_bazro3, pes_model='nep_BaZrO3.txt',
        tnep_model='tnep-BaZrO3-susceptibility.txt', dump_command='dump_polarizability',
        expected_output_file='polarizability.out'),
}

# Repeated runs of the same binary on the same GPU reproduce these outputs bit for bit, so the
# spread to absorb is the one between binaries: another CUDA toolkit, another GPU architecture
# or a change in the evaluation code reorders the fp32 arithmetic, and the five velocity-Verlet
# steps ahead of the last dumped row amplify it. Against the golden file that difference reaches
# 1.1e-6 for the dipole, whose components are of order 1, and 4.6e-6 for the polarizability,
# whose diagonal is of order 1e2 and whose off-diagonal components of order 1e-3 stay within
# 8e-7. atol carries the near-zero components, where a relative bound alone is unstable, and
# both bounds sit an order of magnitude above the differences observed.
TNEP_GOLDEN_TOLERANCE = dict(rtol=1e-4, atol=1e-5)


@pytest.mark.parametrize('case_name', list(TNEP_CASES))
def test_tnep_dump_command(tmp_path, gpumd_command, update_golden, case_name):
    case = TNEP_CASES[case_name]
    atoms = case['structure_builder']()
    pes_path = MODELS_DIR / case['pes_model']
    tnep_path = MODELS_DIR / case['tnep_model']

    def _check_against_golden(path):
        data = np.loadtxt(path)
        if data.ndim == 1:
            data = data.reshape(1, -1)
        compare_or_update_golden(
            f'tnep_{case_name}', {'values': data}, TNEP_GOLDEN_TOLERANCE, update_golden)

    io_case = CommandIOCase(
        name=case_name,
        # Explicit PES potential plus the response model on the dump command -- see the
        # module docstring.
        run_in_lines=[
            ('potential', str(pes_path)),
            (case['dump_command'], [1, str(tnep_path)]),
        ],
        expected_output_files=[case['expected_output_file']],
        parse_check=_check_against_golden,
    )
    run_and_check(tmp_path, atoms, pes_path, 'nep', gpumd_command, io_case)
