"""Command IO smoke tests (Tier 1): TNEP "observer" models (dump_dipole, dump_polarizability).

GPUMD's own output is the ground truth here, per project principle: calorine's separately
maintained CPU reference implementation (CPUNEP, calorine.nep.get_polarizability) is not
guaranteed to support the same features and is not used to validate numeric correctness, in this
file or elsewhere in this suite going forward. Correctness is instead judged the same way
test_regression.py judges bulk_bazro3 -- against a golden reference generated by this repo's own
gpumd binary (conftest.py's compare_or_update_golden), regenerated only via --update-golden.

TNEP models are "observer" models: they run *alongside* a separate PES model rather than
replacing it, via two `potential` lines in run.in (PES first, TNEP observer second) -- see
gpumd_pytest_suite_spec.md's "TNEP fixtures" section. This doesn't fit the calculator/model_type
fixture pattern used elsewhere in this suite (no single model file, no CPUNEP/GPUNEP A/B
comparison to make), so each case wires up its own fixed (structure, PES model, TNEP model)
triple directly rather than sweeping the structure x model_type matrix -- the same reasoning
test_regression.py already applies to bulk_bazro3. The run.in construction pattern (two explicit
`potential` lines in run_in_lines, GPUNEP's auto-prepend suppressed by their presence) mirrors
the existing manual tests at tests/gpumd/dump_dipole/test_dump_dipole.py and
tests/gpumd/dump_polarizability/test_dump_polarizability.py, which remain the reference for
run.in syntax, not for numeric values.
"""
import numpy as np
import pytest

from conftest import MODELS_DIR, compare_or_update_golden, make_bulk_bazro3, make_bulk_water
from io_helpers import CommandIOCase, run_and_check

pytestmark = pytest.mark.fast

TNEP_CASES = {
    'dipole_water': dict(
        structure_builder=make_bulk_water, pes_model='nep_water.txt',
        tnep_model='tnep-water-polarization.txt', dump_command='dump_dipole',
        expected_output_file='dipole.out'),
    'polarizability_bazro3': dict(
        structure_builder=make_bulk_bazro3, pes_model='nep_BaZrO3.txt',
        tnep_model='tnep-BaZrO3-susceptibility.txt', dump_command='dump_polarizability',
        expected_output_file='polarizability.out'),
}

# A single-step run from a fixed seed reproduced bit-for-bit identically across repeated runs
# when calibrating this (no GPU reduction-order noise visible at this trajectory length), so this
# is tighter than TOLERANCES['force'] rather than matching it -- loosen only if genuine run-to-run
# noise is observed later (e.g. on different hardware).
TNEP_GOLDEN_TOLERANCE = dict(rtol=1e-6, atol=1e-8)


@pytest.mark.parametrize('case_name', list(TNEP_CASES))
def test_tnep_dump_command(tmp_path, gpumd_command, update_golden, case_name):
    case = TNEP_CASES[case_name]
    atoms = case['structure_builder']()
    pes_path = MODELS_DIR / case['pes_model']
    tnep_path = MODELS_DIR / case['tnep_model']

    def _check_against_golden(path):
        data = np.loadtxt(path)
        if data.ndim == 1:
            data = data.reshape(1, -1)
        compare_or_update_golden(
            f'tnep_{case_name}', {'values': data}, TNEP_GOLDEN_TOLERANCE, update_golden)

    io_case = CommandIOCase(
        name=case_name,
        # Explicit potential lines (PES, then TNEP observer) rather than relying on
        # make_gpunep's single-model setup -- see module docstring.
        run_in_lines=[
            ('potential', str(pes_path)),
            ('potential', str(tnep_path)),
            (case['dump_command'], 1),
        ],
        expected_output_files=[case['expected_output_file']],
        parse_check=_check_against_golden,
    )
    run_and_check(tmp_path, atoms, pes_path, 'nep', gpumd_command, io_case)
